### PR TITLE
Enable python 35

### PR DESCRIPTION
**Pull request by hackebrot**
Python 3.5 is out and we don't seem to have any incompatibilities :rocket:

### CODE REVIEW

**Comment by hackebrot** [comment]
Hmmm.. https://github.com/mitsuhiko/jinja2/pull/495/files

**Comment by maiksensi** [comment]
How should we proceed? I suggest we integrate the changes from #524. 
To get this working (almost) merge my changes from PR #523 to your branch. Then reapply all your changes, but change the ```appveyor.yml``` accordingly to the changes from PR #523 . 
To get Travis-CI working integrate my changes, which change the base python install (and thus downloads it): https://github.com/maiksensi/cookiecutter/blob/feat/support-for-py35/.travis.yml
This will result in one last failing check (flake8). Which I didn't have a look at yet.

**Comment by pydanny** [comment]
Err... I just merged in #523. Maybe that was premature, but in hindsight this PR (#522) should be built off of it.

**Comment by hackebrot** [comment]
Rebase :smile_cat:

**Comment by maiksensi** [comment]
I am not sure, but I think a newer '''tox.ini''' (with py35 in the matrix) slipped through, which will not work in travis currently.

**Comment by hackebrot** [comment]
Yes, see 8e69a492c.

As it is working completely fine locally, we can possibly deactivate it on travis only.

What's your opinion on this?

**Comment by audreyr** [comment]
I think deactivating 3.5 on Travis only for now would be alright.

**Comment by zoidbergwill** [comment]
What about configuring tox in Travis using a matrix like [pip does](https://github.com/pypa/pip/blob/develop/.travis.yml#L4-L33)?

**Comment by maiksensi** [comment]
@zoidbergwill 
> What about configuring tox in Travis using a matrix like pip does? 

Together with Tox, this would move build logic from Tox to Travis which I think is confusing. We would also need to change the tox config, as the pip like configuration would create a matrix with many redundant tox tests. I would also just wait till travis-ci adds py35 as an alias, as all tests run fine locally. There's also appveyor as "backup" CI which already works fine with py35.

**Comment by hackebrot** [comment]
The scope of this PR slightly changed. :no_mouth: 

It adds Python 3.5 to the docs and appveyor. That's pretty much it.

Please let me know your feedback!

**Comment by maiksensi** [comment]
:+1:

**Pull request merged**
