### PR TITLE
Add cookiecutter-latex-article to list of LaTeX templates.

### PR DESCRIPTION
**Pull request by Kreger51**
Hi!

I would be pleased if you would add my template to the list.

I'm currently a student and use this template to write my lab reports/essays and basically anything that I don't do by hand. However, it could be used for anything that makes use of the ``article`` document class. 

The template can be found at: https://github.com/Kreger51/cookiecutter-latex-article. 

Appreciate the utility by the way!

Thanks, 

Selim

### CODE REVIEW

**Comment by msabramo** [comment]
Looks trivial to merge. :+1:

**Comment by pydanny** [comment]
Merging in.

FWIW, we actually like to examine and try the cookiecutter templates before we add them to the list.

**Comment by msabramo** [comment]
Ah, good to know that you try them. That means the decision to merge isn't quite as trivial as I might've imagined.

**Comment by Kreger51** [comment]
Thanks! Cool to know you try them indeed.

**Pull request merged**
