### PR TITLE
Add support for ignore rendering files listed in cookiecutter.json

### PR DESCRIPTION
**Pull request by osantana**
You can add a key `_ignore_files` in your cookiecutter.json containing
a list of filenames (or a globs) that will be skipped on rendering.

### CODE REVIEW

**Comment by pydanny** [comment]
A number of people have asked about this recently. Anyone want to pick up on this where it was left off?

**Comment by hackebrot** [comment]
Hi @osantana @LucianU do you want to continue on this one?

It seems the fork doesn't exist any more. So I can't really check what the conflicts are.

I could help with integrating the test into the new suite :construction_worker:

**Comment by osantana** [comment]
Hi @hackebrot,

I'm not interested anymore. I dropped support for cookiecutter on my project and created a custom "installation" script.

**Comment by hackebrot** [comment]
Thanks for your fast reply @osantana 

Sorry to hear that :cry:

**Comment by LucianU** [comment]
Hi, @hackebrot. What do you mean the fork doesn't exist? Isn't this it https://github.com/audreyr/cookiecutter/pull/184?

I still use cookiecutter, but I just use my fork for now, because I don't have an issue with that. I don't use Windows and my time is limited, so I don't know how I could help though.

**Comment by hackebrot** [comment]
I was talking about this PRs fork. Must have missed #184. Thanks :bow:

Guess we can close this one then, right?

**Comment by pydanny** [comment]
Closing this with many thanks to @osantana. It took a while, but your concept is now part of cookiecutter and will be in the 1.1 release!

**Pull request closed without merging**
