### PR TITLE
Added new cookiecutter template

### PR DESCRIPTION
**Pull request by kkujawinski**
Template for Sublime Text 3 plugin.

### CODE REVIEW

**Comment by hackebrot** [comment]
Hi @kkujawinski!

Thank you for submitting this template. Having a brief look at the template, I noticed two things:

* Can you please add a link to **Cookiecutter** to your README?
* Your project itself does not have a LICENSE file

**Comment by kkujawinski** [comment]
done.

**Comment by hackebrot** [comment]
From what I can see your sublime plugin mostly uses Javascript. Can you please move it to the according section in our README?

**Comment by kkujawinski** [comment]
Default language for Sublime Text plugins is Python ({{cookiecutter.plugin_internal_name|replace('-', '_')}}.py file). Configuration files are in json, but there are no Java Script code.

**Pull request merged**
