### PR TITLE
Add jinja2 time

### PR DESCRIPTION
**Pull request by hackebrot**
Support for current date time in prompt and generation via ``{% now 'utc' %}``.

Please let me know your thoughts! :bow: 

Related to #617

### CODE REVIEW

**Comment by michaeljoseph** [comment]
:bell: Looks like this needs a little rework because #617...

**Comment by hackebrot** [comment]
Hi @michaeljoseph! :wave: 

Getting all these notifications for your comments made my day :smiley: 

Do you think we should add ``jinja2-time`` to cookiecutter itself? This was supposed to be an easy alternative to #617 as it was sitting there for a while and people kept asking about it.

**Comment by hackebrot** [comment]
I'd love to get this to core, in the end of the day every template uses either ``year`` or ``now``. Both of which easily be retrieved with **jinja2-time**. :smile:

**Comment by michaeljoseph** [comment]
Hey @hackebrot :smiley_cat: 
Yeah, I'm :+1: on including *jinja2-time*.

**Comment by hackebrot** [comment]
Aye, I'll update this guy and release a new version. Sounds good to you @michaeljoseph @pydanny?

**Comment by hackebrot** [comment]
Updated version at #653 :smiley:

**Pull request closed without merging**
