### PR TITLE
Update usage.rst

### PR DESCRIPTION
**Pull request by msbanik**
Permission denied when `git clone git@github.com:audreyr/cookiecutter-pypackage.git`

### CODE REVIEW

**Comment by pydanny** [comment]
The existing method works for me on both Mac OSX and Linux. @msbanik, maybe there is something specific to your setup?

**Comment by msbanik** [comment]
It's works for you because you have the ssh key of the repo.

**Comment by pydanny** [comment]
@msbanik - Do you get an error message that looks like:
``` bash
$ git clone git@github.com:audreyr/cookiecutter-pypackage.git
Initialized empty Git repository in /app/cookiecutter-pypackage/.git/
The authenticity of host 'github.com (192.30.252.131)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
```

**Comment by msbanik** [comment]
λ git clone git@github.com:audreyr/cookiecutter-pypackage.git
Cloning into 'cookiecutter-pypackage'...
Warning: Permanently added the RSA host key for IP address '192.30.252.131' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by michaeljoseph** [comment]
@msbanik https://help.github.com/articles/error-permission-denied-publickey/

**Comment by msbanik** [comment]
Solved, thanks @pydanny and @michaeljoseph

**Pull request closed without merging**
