### PR TITLE
add a jsonify filter to jinja default extensions

### PR DESCRIPTION
**Pull request by aroig**
This enables a template like this

```
{{ cookiecutter | jsonify }}
```

that renders the a python object as json, as suggested in #784

### CODE REVIEW

**Comment by hackebrot** [comment]
Hey @aroig, thank you for submitting this PR so quickly 😄 

I'd be okay with adding this extension. Let's see what the others think.

That being said, before we can accept this change, we would need to have tests for it. Can you please add a couple of tests? I'd like to see at least one example for how a template would use this new extension in an automated test that we can leverage for identifying regressions.

Thanks!

**Comment by hackebrot** [comment]
@aroig can you please add tests for this?

**Comment by aroig** [comment]
@hackebrot Sorry for the delay. I'm quite busy at the moment, but I'll try to find the time.

**Comment by hackebrot** [comment]
@aroig ok, cool. Thank you 🙇

**Comment by aroig** [comment]
@hackebrot I pushed a test for this. Let me know if you want me to write any kind of documentation.

**Comment by hackebrot** [comment]
The test fails 😿

**Comment by aroig** [comment]
Sorry about that. The test passed locally, but obviously was too fragile. It turns out python versions differ on how they render spaces in json...

I force pushed a second attempt.

**Comment by aroig** [comment]
I see this is still tagged as "needs tests". I pushed them some time ago and they pass. Is there anything else to be done?

**Comment by hackebrot** [comment]
Hey @audreyr @pydanny @michaeljoseph! 👋 

What's your opinion on this?

**Comment by hackebrot** [comment]
Thank you @aroig! 🍪

**Pull request merged**
