### PR TITLE
Specify user config file via cli or environment variable

### PR DESCRIPTION
**Pull request by hackebrot**
Retrieve the user config file from a custom location via:

``$ cookiecutter --config /home/audreyr/my-custom-config.yaml cookiecutter-pypackage``

or

``$ export COOKIECUTTER_CONFIG=/home/audreyr/my-custom-config.yaml``

**``--config`` takes precedence over ``COOKIECUTTER_CONFIG`` over ``~/.cookiecutterrc``.**

Close #424, close #258 cc @jhermann @pfmoore

### CODE REVIEW

**Comment by hackebrot** [comment]
Review pls :bow:

**Comment by hackebrot** [comment]
Rebased :triumph:

**Comment by pydanny** [comment]
Oh no https://ci.appveyor.com/project/audreyr/cookiecutter/build/1.0.765/job/72echyrph19hui4r

:weary:

**Comment by hackebrot** [comment]
Can you trigger a rebuild, please? Errors seem to be ``git`` related. Thanks :bow:

**Comment by hackebrot** [comment]
Nvm, removed an obsolete **TODO** :joy_cat:

**Comment by hackebrot** [comment]
Take that, appveyor! :facepunch:

**Comment by luzfcb** [comment]
> Take that, appveyor! :facepunch:

I laughed :smile_cat:

**Comment by pydanny** [comment]
Ha ha ha. :last_quarter_moon_with_face:

**Comment by hackebrot** [comment]
Hrhr :trollface:

**Comment by hackebrot** [comment]
## TODO
- [ ] support forced default config
- [ ] do not break backwards compatibility in cli and main
- [ ] fix test failures

**Comment by hackebrot** [comment]
Added support for ignoring a user config altogether via ``--default-config`` or passing ``None`` to ``main.cookiecutter``.

I feel this PR drastically improves the ability to write isolated tests. :rocket:

**Pull request merged**
