### PR TITLE
Added flask-extension-cookiecutter

### PR DESCRIPTION
**Pull request by Olamyy**

### CODE REVIEW

**Comment by hackebrot** [comment]
Hi @Olamyy! 👋 

Can you please fix the link to Cookiecutter on the template's README file?

**Comment by hackebrot** [comment]
Looks like the [flask extension's README](https://github.com/Olamyy/flask-extension-cookiecutter/tree/master/%7B%7Bcookiecutter.extension_folder_name%7D%7D) is not correct, as it describes how to generate an extension.

**Comment by hackebrot** [comment]
:bell:

**Comment by theodesp** [comment]
@Olamyy Can you update or remove the readme here https://github.com/Olamyy/flask-extension-cookiecutter/tree/master/%7B%7Bcookiecutter.extension_folder_name%7D%7D ?

**Comment by hackebrot** [comment]
Please open a new PR if you're still interested in adding your template @Olamyy! Thank you 🙇

**Pull request closed without merging**
