### PR TITLE
Ensure file handles are closed using with statement

### PR DESCRIPTION
**Pull request by svisser**
This change ensures the file handles are closed properly in setup.py.

### CODE REVIEW

**Comment by msabramo** [comment]
I don't see the benefit of using `with` in `setup.py` since it is short-running and files get closed on exit. 

One line is nicer to read.

**Comment by svisser** [comment]
I think standard practise also applies to `setup.py`, it shouldn't be treated differently just because the process is short-lived.

**Comment by pydanny** [comment]
I think demonstrating good practices overrides the desire for just a few less lines of code.

FWIW, Audrey says the original reason why `setup.py` was written this way was because she thought Python 2.6 didn't have the `with` statement.

**Comment by svisser** [comment]
Thank you!

**Pull request merged**
