### PR TITLE
Complain if we can't locate a local repository

### PR DESCRIPTION
**Pull request by michaeljoseph**
Addresses the stack trace in #385.

### CODE REVIEW

**Comment by hackebrot** [comment]
Hmm isn't test_replay.py useless now as the test will error out before the assertions are hit?

**Comment by pydanny** [comment]
Hmmmm... You might be right.

**Comment by hackebrot** [comment]
Currently working on the ``jinja2_time`` PR.

Can you please revert the changes in **test_replay.py** and replace ``foobar`` with ``tests/fake-repo-tmpl`` in it? Should do the trick.

**Comment by hackebrot** [comment]
Wrote a tiny test :grin: Do want the coverage to drop, please review 6fed44e26539e607e60acdc39aa73a69e769ec5f on **master**

**Comment by michaeljoseph** [comment]
:grimacing: thanks for the fixes @hackebrot

**Pull request merged**
