### PR TITLE
python-future support

### LINKED ISSUE #298: Address test coverage issues for compat.py
Currently `cookiecutter.compat` gets a pass on testing via `pragma: no cover`. Yes, we have tox on all the other stuff, but it ain't right. I'm opening this ticket because I believe through creative use of `mock.patch` we can have appropriate tests and remove those nasty  `pragma: no cover` statements.

This follows on #203 and #252.

On the other hand, if we decide to add another dependency and include `six`, this becomes moot.

### LINKED ISSUE #301: Consider moving to six or future for Python 2/3 compatibility
**Should we move to one of these libraries?** I think so, as it would mean we could nearly eliminate the `compat.py` module, improving test coverage.

**Which library?** `six`, `future`, or something else?

### PR DESCRIPTION
**Pull request by michaeljoseph**
Fixes #301
Fixes #298

### CODE REVIEW

**Comment by hackebrot** [comment]
I'm voting for ``click`` to handle all the CLI prompting which is currently part of ``compat.py``.

Please see #443

**Comment by pydanny** [comment]
As we are using `click` for CLI prompting, what should we do with this pull request?

**Comment by hackebrot** [comment]
Guess we don't really need it any longer, am I right @michaeljoseph? :no_mouth:

**Comment by hackebrot** [comment]
:bell:

**Comment by michaeljoseph** [comment]
@hackebrot yeah, let's close, this will need to be reworked.

**Pull request closed without merging**
