### PR TITLE
Use poyo for user rc files

### PR DESCRIPTION
**Pull request by hackebrot**
I wrote a YAML parser for simple files. :chicken: 

https://pypi.python.org/pypi/poyo

It should be fine for ``cookiecutterrc`` files and may help us overcome the troubles with **PyYAML** and **ruamel.yaml** (#557, #569). :worried:

### CODE REVIEW

**Comment by pydanny** [comment]
I'm having trouble getting this PR to pass tests locally. This is an example error:

```
config_path = '/Users/danielgreenfeld/.cookiecutterrc'

    def get_config(config_path):
        """
        Retrieve the config from the specified path, returning it as a config dict.
        """
    
        if not os.path.exists(config_path):
            raise ConfigDoesNotExistException
    
        logger.debug('config_path is {0}'.format(config_path))
        with io.open(config_path, encoding='utf-8') as file_handle:
            try:
                yaml_dict = poyo.parse_string(file_handle.read())
            except poyo.exceptions.PoyoException as e:
                raise InvalidConfiguration(
                    'Unable to parse YAML file {}. Error: {}'
>                   ''.format(config_path, e)
                )
E               cookiecutter.exceptions.InvalidConfiguration: Unable to parse YAML file /Users/danielgreenfeld/.cookiecutterrc. Error: None of the known patterns match for default_context
E                   full_name:
E                   email: "firstname.lastname@gmail.com"
E                   github_username: "example"
E               cookiecutters_dir: "/home/example/some-path-to-templates"

cookiecutter/config.py:49: InvalidConfiguration
```

**Comment by pydanny** [comment]
Poyo's tests pass for me, but this PR fails. I've rebuilt my `virtualenv` and `tox` environments a few times to no avail. Digging into to see where the problem is...

**Comment by pydanny** [comment]
The problem was on my end with a corrupted `.cookiecutterrc` file. By corrupted, it had a borked line ending.

**Comment by vincentbernat** [comment]
Would it be possible to support whatever YAML parser is already present on the system? I can't package (and maintain) all the YAML parsers on earth just to get cookiecutter in Debian.

**Comment by hackebrot** [comment]
@vincentbernat I'd prefer to get rid of YAML altogether

**Comment by pydanny** [comment]
The problem we have is that the other YAML parsers for Python aren't maintained (PyYAML) and fail in some places or are maintained (Raumel.YAML) and fail in others. The area of failure is over multiple operating systems and versions of python. Trying to gracefully allow local parsers of YAML is actually challenging.

Creative setup.py configurations are tricky to try and garantee. We know because we tried. And ran into many problems.

Poyo is pure python. It works everywhere. By breaking it into its own project we can better test it against multiple python distress and multiple flavors of Linux, OSX, and Windows.

**Comment by vincentbernat** [comment]
In Debian, both of them work fine and the problems they have on other OS do not really concern us. With poyo, I need to introduce a new package whose description would be something like "pure Python YAML parser that doesn't really parse YAML". I will be told that such a package shouldn't be in Debian (not because it doesn't do its job but because we already have two YAML parsers for Python and it would be odd to introduce another one that only accepts a subset of YAML).

I can just patch my copy of cookiecutter to use PyYAML or ruamel.yaml if you don't want more work on this. Would this be OK?

**Comment by vincentbernat** [comment]
FYI, I applied the following patch to avoid an additional dependency: http://sources.debian.net/src/cookiecutter/1.4.0-1/debian/patches/0002-Use-PyYAML-instead-of-poyo.patch/

**Comment by hackebrot** [comment]
Thanks for the update @vincentbernat! 🙇

**Pull request merged**
