### PR TITLE
Add config prompt design inspired by bower and npm

### PR DESCRIPTION
**Pull request by robinandeer**
Note: the original PR (#207) was botched - this is my second attempt.

---

Very simple update (no changes to code execution) and therefor no added tests.

Simply a cleaner config prompt, inspired by bower and npm.

Before: `full_name (default is "Your full name")?`
After: `full_name: (Your full name)`

/cc @michaeljoseph 

EDIT: updated prompt preview to reflect discussion below, removed prepended `[?]`.

### CODE REVIEW

**Comment by msabramo** [comment]
I agree on removing the `[?]` and this needs to be rebased now b/c of conflicts.

**Comment by pydanny** [comment]
Anyone else want to weigh in on this one? I'm on the fence.

**Comment by msabramo** [comment]
It doesn't seem like much of an improvement and it's not merging cleanly so if I were the maintainer I would probably close the PR. But I'll let others weigh in.

**Comment by robinandeer** [comment]
I just thought it looked good with the question mark added, but I'd be happy to remove that part. I still think the simplified look is an improvement over the current prompt  :-)

If the merge conflict is the problem I'm holding off since last time I tried rebasing an already pushed branch, the history was totally botched. Oops.

Weather or not you decide to go with this updated prompt or not I would very much appreciate if anyone can point me to a nice resource on how to rebase a pull request!

**Comment by msabramo** [comment]
@robinandeer: Try something like:

```
git checkout cleaner-config-prompt-v2
git fetch origin
git rebase origin/master
# If there are conflicts, they will be listed and you must fix them and then do `git add <file>` on each one and when you are done do `git rebase --continue`.
# Test the final result
git push -f robinandeer cleaner-config-prompt-v2
```

**Comment by msabramo** [comment]
And for more details check out https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by robinandeer** [comment]
Thank you so much @msabramo! This seems exactly like what I was looking for :smile:

**Comment by robinandeer** [comment]
I've learned something new today! The reason I messed up before was because I didn't do a ``git push --force`` correctly before after the rebase (it's not built into SourceTree :sweat_smile:).

Thanks again! I've also remove the ``[?]`` from the prompt in this suggestion.

**Comment by michaeljoseph** [comment]
:+1:

**Comment by hackebrot** [comment]
Cookiecutter now uses click for prompting, see #455.

Thank you for the PR though, @robinandeer! 🙇

**Pull request closed without merging**
