### PR TITLE
Include template directory or url in the context dictionary

### PR DESCRIPTION
**Pull request by aroig**
This is one use case: Have a make target in the rendered project that
pulls changes from the template source, renders the up-to-date template
with the same context used to create the project, and then merges the
changes back into the rendered project.

### CODE REVIEW

**Comment by aroig** [comment]
By the way, I'm not sure why travis tests fail. If you accept merging something like this, I can fix any test that needs fixing and add documentation or an entry in history.

**Comment by aroig** [comment]
I force-pushed a fix for the tests.

**Comment by hackebrot** [comment]
Hi @aroig! 👋 

Thank you for opening a PR for this.

What do you think @audreyr @pydanny @michaeljoseph?

**Comment by hackebrot** [comment]
Thank you for your contribution @aroig! 🍪

**Pull request merged**
