### PR TITLE
Extend CLI help message

### PR DESCRIPTION
**Pull request by hackebrot**
I'm not sure if this is something we want, but wanted to at least discuss it.

```text
$ cookiecutter --help
Usage: cookiecutter [OPTIONS] TEMPLATE [EXTRA_CONTEXT]...

  Create a project from a Cookiecutter project template (TEMPLATE).

  Cookiecutter is free and open source software, developed and managed by
  volunteers. If you would like to help out or fund the project, please get
  in touch at https://github.com/audreyr/cookiecutter.

Options:
  -V, --version              Show the version and exit.
  --no-input                 Do not prompt for parameters and only use
                             cookiecutter.json file content
  -c, --checkout TEXT        branch, tag or commit to checkout after git clone
  -v, --verbose              Print debug information
  --replay                   Do not prompt for parameters and only use
                             information entered previously
  -f, --overwrite-if-exists  Overwrite the contents of the output directory if
                             it already exists
  -o, --output-dir PATH      Where to output the generated project dir into
  --config-file PATH         User configuration file
  --default-config           Do not load a config file. Use the defaults
                             instead
  --debug-file PATH          File to be used as a stream for DEBUG logging
  -h, --help                 Show this message and exit.
```

### CODE REVIEW

**Comment by michaeljoseph** [comment]
:heart: from me.

**Comment by hackebrot** [comment]
@audreyr @pydanny? 😄

**Comment by pydanny** [comment]
Huge ❤️  from me. 😄

**Comment by hackebrot** [comment]
Awesome! Thanks everybody 🍪

**Pull request merged**
