### PR TITLE
Added Wagtail Cookiecutter

### PR DESCRIPTION
**Pull request by tkjone**
New wagtail Cookiecutter added to the Django Cookiecutters list.

### CODE REVIEW

**Comment by hackebrot** [comment]
Hi @tkjone :wave: 

I'm afraid your README file is incorrect. It looks like you've copied stuff from [django-starter](https://github.com/tkjone/django-starter) :confused:

**Comment by tkjone** [comment]
Thanks @hackebrot for the catch!  Resolved incorrect links and references in the README - [wagtail-starter-kit](https://github.com/tkjone/wagtail-starter-kit)

**Comment by hackebrot** [comment]
Sorry but you template does not work (See error below). :disappointed: 
```python
Unable to create file 'src/server/.pylintrc'
Error message: 'dict object' has no attribute 'use_celery'
Context: {
    "cookiecutter": {
        "author_email": "admin@gmail.com",
        "author_name": "admin",
        "current_year": "2016",
        "db_engine": "sqlite",
        "db_host": "localhost",
        "db_name": "wagtailstuff",
        "db_password": "wagtailstuff_dev",
        "db_user": "dev",
        "django_default_settings": "config.settings.dev",
        "django_reqs_path": "wagtailstuff/src/dev.txt",
        "domain_name": "example.com",
        "full_legal_name_of_project_owner": "",
        "license": "No License",
        "os_user": "vagrant",
        "project_name": "src",
        "project_root_path": "wagtailstuff/src",
        "repo_name": "wagtailstuff",
        "repo_root_path": "wagtailstuff",
        "virtualenv_dir_path": "wagtailstuff/venvs"
    }
}
```

Please add tests with [pytest-cookies](https://github.com/hackebrot/pytest-cookies) or something similar. Example tests at [cookiecutter-django](https://github.com/pydanny/cookiecutter-django/blob/master/tests/test_cookiecutter_generation.py#L53)

On a different note, you may want to template your variables so that it does not point to ``/home/vagrant/`` for each var.

```json
{
    "repo_root_path": "/home/vagrant/{{cookiecutter.repo_name}}",
    "project_root_path": "{{cookiecutter.repo_root_path}}/src",
    "django_reqs_path": "{{cookiecutter.repo_root_path}}/src/server/requirements/dev.txt",
}
```

**Comment by tkjone** [comment]
@hackebrot thanks again!  Resolved the issue with use_celery.  Will add tests.  What do you mean by template the above variables to no point to `/home/vagrant/`?

**Comment by hackebrot** [comment]
Sounds good! :clap:

**Comment by tkjone** [comment]
@hackebrot I added the tests.  Now, I could not get them to pass, but I am able to build the project and it is working.  Curious about why they are failing.  I clones cookiecutter-django and I ran those tests and they also failed...is there something I am doing wrong?

I am using pytest-cookies and run `py.test` inside of the tests directory.  Getting a  `+  where -1 = <Result IOError(2, 'No such file or directory').exit_code`.

**Comment by hackebrot** [comment]
Please try to run ``py.test`` from the root of the repo instead of inside of the tests folder.

**Comment by hackebrot** [comment]
If you want this still in, please get back to us and rebase your branch to solve conflicts :bow:

**Comment by hackebrot** [comment]
:bell:

**Comment by tkjone** [comment]
Sorry!  I am going to close this and fix.

**Pull request closed without merging**
