### PR TITLE
add cookiecutter_dotfile

### PR DESCRIPTION
**Pull request by bdcaf**

### CODE REVIEW

**Comment by hackebrot** [comment]
Hi @bdcaf! 👋 

Can you please add a link to Cookiecutter to your template's README file?

**Comment by bdcaf** [comment]
Sure.  Is it OK like this - or how would you prefer it?

**Comment by hackebrot** [comment]
Cool! Thanks 👍

**Comment by hackebrot** [comment]
Looks like this was already added in #925. I was quite confused right now why the merge commit doesn't contain any changes 😁

**Pull request merged**
