### PR TITLE
Add replay feature

### PR DESCRIPTION
**Pull request by hackebrot**
This PR adds a great feature to **Cookiecutter**! :smile_cat: 

Users can now *replay* their previous invocation without being prompted for input again by adding ``--replay`` on the cli or setting the according kwarg when using the api. This feature is comes in handy if you want to create a new project from an updated template. Cookiecutter now dumps a json  to ``~/.cookiecutter_replay/`` when you call it (it overwrites per name).

```bash
[raphael@hackebook ~]$ tree .cookiecutter_replay/
.cookiecutter_replay/
├── cookiecutter-django.json
└── cookiedozer.git.json
```
Cookiecutter uses these *replay files* if you pass the aforementioned cli option.

@ionelmc and I had a chat on this feature at EuroPython, so I decided to spend some time on it. 

**Note**: I am going to update this PR in the upcoming days with an according section in our advanced usage docs.

Please let me know your thoughts! Any feedback is welcome :bow:

### CODE REVIEW

**Comment by ionelmc** [comment]
Whoa! :cake: 

Do I understand the changes correctly, to regenerate a project you run `cookiecutter --replay project-name`?

**Comment by hackebrot** [comment]
First you run **Cookiecutter** as you are used  to:

```bash
cookiecutter https://github.com/pytest-dev/cookiecutter-pytest-plugin.git
```
If you wish to use the template again without going through the variables you add the according option:

````bash
cookiecutter https://github.com/pytest-dev/cookiecutter-pytest-plugin.git --replay
```
I'll write a brief guide for the docs soon :smiley:

**Comment by ionelmc** [comment]
How do I regenerate a project that was generated some time ago (certainly not the last project)?

**Comment by hackebrot** [comment]
Well if you don't have a replay file.... you could add it yourself :smiling_imp: 

See https://github.com/hackebrot/cookiecutter/blob/add-replay-feature/tests/test-replay/cookiedozer_load.json

**Comment by ionelmc** [comment]
I mean, how does `cookiecutter https://github.com/pytest-dev/cookiecutter-pytest-plugin.git --replay` know what project to replay? 

Maybe I just need to wait on the docs. Or read more code :grin:

**Comment by hackebrot** [comment]
https://github.com/audreyr/cookiecutter/pull/501/files#diff-15d53d64fa153c578d1489460db0a98aR96

**Comment by hackebrot** [comment]
Anyone up for a review? @ionelmc @audreyr @pydanny @michaeljoseph

**Comment by pydanny** [comment]
I like how this separates as much of possible of the new functionality into new areas of code, rather than spiking the whole project. I'm testing it on `cookiecutter-django`, as that has gotten to be a rather sophisticated template.

**Comment by pydanny** [comment]
What is missing is documentation, otherwise methinks this is complete and would be an awesome feature for 1.1.0.

**Comment by hackebrot** [comment]
Thank you for your review and feedback @pydanny! :bow: 

I was actually about to write the docs when I discovered #502. I'll update this PR later on! :smile_cat:

**Comment by hackebrot** [comment]
Docs done :triumph:

**Comment by audreyr** [comment]
I went through this in detail too. It looks fantastic. Amazing work @hackebrot!

**Comment by hackebrot** [comment]
Thank you @audreyr! :blush:

**Pull request merged**
