### PR TITLE
Add new django template optimized for heroku

### PR DESCRIPTION
**Pull request by dulaccc**
This new package differs from the `cookiecutter-django` repo, because it is oriented Python 3 only, and has clean optimizations for Heroku only.

Cheers

### CODE REVIEW

**Comment by michaeljoseph** [comment]
@dulaccc You need to add a line to reference this link too...

**Comment by dulaccc** [comment]
^^ feeling a little ashamed... let me fix that !

**Comment by pydanny** [comment]
Weird. Travis-CI failed. Restarting the build.

**Comment by pydanny** [comment]
Failed again on flake8 for 2.7. I'll look into this later today.

**Comment by michaeljoseph** [comment]
So, [`flake8` pins it's `pep8` dependency](https://gitlab.com/pycqa/flake8/issues/32)  ["the wrong way"](https://gitlab.com/pycqa/flake8/blob/master/setup.py#L53), so we're now using pep 1.6, which has [this new check](https://github.com/jcrocholl/pep8/issues/277).
The easiest fix is probably a `.flake8` to ignore it.

**Comment by michaeljoseph** [comment]
#390 adds a `setup.cfg` to ignore E731.

**Comment by pydanny** [comment]
Since I've merged in @michaeljoseph's #390, I've restarted the Travis CI build.

**Comment by pydanny** [comment]
@dulaccc Could you rebase this from master? You need to pick up @michaeljoseph's code from #390 in order to have this pass on Travis.

**Comment by dulaccc** [comment]
Of course, I'll do that.

**Comment by audreyr** [comment]
Nice work @dulaccc. Once you merge https://github.com/dulaccc/cookiecutter-django-herokuapp/pull/1, we can merge this PR in.

**Comment by pydanny** [comment]
🔔

**Comment by dulaccc** [comment]
Done :) sorry for the delay, I've merged the dulaccc/cookiecutter-django-herokuapp#1 PR

**Pull request merged**
