### PR TITLE
add cookiecutter-funkload-friendly template to python list

### PR DESCRIPTION
**Pull request by tokibito**

### CODE REVIEW

**Comment by michaeljoseph** [comment]
:+1: :smiley_cat:

**Comment by hackebrot** [comment]
Can you please update HISTORY? :bow:

**Comment by tokibito** [comment]
Thanks for merge. I updated the HISTORY.

**Comment by michaeljoseph** [comment]
@tokibito I think that was for me :blush: 
@hackebrot 899ca8a

**Comment by hackebrot** [comment]
Thanks :bow:

**Pull request merged**
