### PR TITLE
Add beat-generator to the README file

### PR DESCRIPTION
**Pull request by ruflin**

### CODE REVIEW

**Comment by hackebrot** [comment]
Hi @ruflin, thank you for submitting a template.

Can you please fix the rst link?

**Comment by ruflin** [comment]
Sorry for the typo, new version pushed.

**Comment by hackebrot** [comment]
Can you please link back to this project from the template's README?

**Comment by michaeljoseph** [comment]
@ruflin Could you also please update the [list of template categories](https://github.com/audreyr/cookiecutter/blob/master/README.rst#categories-of-cookiecutters)

**Comment by ruflin** [comment]
@michaeljoseph I will update the categories.
@hackebrot Will link to cookiecutter from this README here: https://github.com/elastic/beat-generator Just realised this definitively an update also on how to install cookiecutter ... ;-)

**Comment by ruflin** [comment]
@michaeljoseph Category introduced. Please have a look. Update of beat-generator README will happen in the next days.

**Comment by ruflin** [comment]
@hackebrot Here is the PR to link to cookiecutter: https://github.com/elastic/beat-generator/pull/40 Anything else you need from my side to move this PR forward?

**Comment by michaeljoseph** [comment]
lgtm :+1:

**Pull request merged**
