### PR TITLE
Copy without render

### PR DESCRIPTION
**Pull request by LucianU**
This continues the work started in PR #132. Looking forward to your feedback.

### CODE REVIEW

**Comment by lanshark** [comment]
So, is this idea dead?  REALLY need this for ansible scripts

**Comment by pydanny** [comment]
@ianshark, This is is not dead at all. I want this to work! However, getting this to work on all platforms is a must for Cookiecutter pull requests. Unfortunately, this PR is not passing all tests on all platforms and fixing that takes free time that we just don't have. Even evaluating PRs takes time we don't have. The issue is that we have to focus on jobs and gigs that pay the bills. What time is left for open source is unfortunately not that much, and usually dedicated to emergencies or smaller tasks that we can resolve in minutes rather than hours.

We've considered adding a donation button in order to have paid time for Cookiecutter. Do you think that would be a good idea? Would you or your company be willing to donate for professional quality work on this particular issue? If so, then I'll add it today and we'll be able to get on the problem right now.

**Comment by lanshark** [comment]
Hmm,

Hi Danny!

Wow - didn't expect to get an answer that quick!  I certainly understand 
the problem.  I'm a full-time contractor too!  Donations are always a 
good idea...but don't expect to get a lot of money that way, unfortunately.

I would be willing to work on the problem.  Is there a branch that's 
attempted to merge this?  What tests are failing?  I have the time to 
dedicate, and it's that important to me.  But I didn't want to step on 
toes, since it looked like it was in progress.

Let me know how I can help!

-Scott

**Comment by pydanny** [comment]
@lanshark - it's pretty frustrating because myself, @audreyr, and @michaeljoseph would love to put more time into this project, especially in regards to the review of pull requests. We're trying to figure out a way to fund development, since this is a very favorite project of ours.

In any case, this PR is failing on Windows tests (what @appveyor tests). That is what needs to be fixed AFAIK.

**Comment by pydanny** [comment]
@hackebrot Everyone would love to see this work. The challenge, of course, is windows.

**Comment by hackebrot** [comment]
@pydanny Yeah I understand and I agree 100% that we should try to get this in. I thought about closing #132 and focussing on #184 instead. :relaxed:

**Comment by hackebrot** [comment]
:bell: Copy without render is now available on master! :smiley: 

See http://cookiecutter.readthedocs.org/en/latest/advanced_usage.html#copy-without-render

**Comment by elbaschid** [comment]
:trophy:

**Comment by pydanny** [comment]
Closing this with many thanks to @LucianU!

**Comment by LucianU** [comment]
Happy to have contributed and happy to see this merged in.

**Comment by clarkevans** [comment]
Danny, I realize doing releases is always work, but it'd be great if this were released to pypi. 
Do you know when you'll have a point release?  We use this feature for our cookie-cutters.
Thank you so much.

**Comment by pydanny** [comment]
Hopefully this week. We have a period of slowdown between now and the arrival of what is hopefully the last proof of our book. Which means maybe tomorrow.

**Pull request closed without merging**
