### PR TITLE
implemented: https://github.com/audreyr/cookiecutter/issues/127

### PR DESCRIPTION
**Pull request by bogensberger**
generate_file() ignores the creation of file if its filename is empty.

### CODE REVIEW

**Comment by jstasiak** [comment]
+1, this is really useful

**Comment by myyk** [comment]
+1, This would be super useful.

**Comment by thomaslee** [comment]
+1, jinja misinterprets code `gradlew` scripts in Gradle projects & breaks hard. Might be possible to work around the issue with hooks, but doing so seems pretty hacky.

**Comment by hackebrot** [comment]
@thomaslee how about [copy-without-render](http://cookiecutter.readthedocs.org/en/latest/advanced_usage.html#copy-without-render)? :confused:

**Comment by thomaslee** [comment]
@hackebrot my bad -- looks like exactly what I'm after!

**Comment by pydanny** [comment]
This can be done in post-generate hooks as seen in https://github.com/pydanny/cookiecutter-django/blob/master/hooks/post_gen_project.py#L163-L165. This makes this issue more an education issue then a technical solution. This is good because making logic work in directory/file names on Windows is impossible (and we support Windows).

Therefore, I believe this is better done as a recipe described in the [advanced_usage.rst](https://github.com/audreyr/cookiecutter/blob/master/docs/advanced_usage.rst) document.

**Pull request closed without merging**
