### PR TITLE
don't remove project directory on failed hook w/ --overwrite-if-exists

### PR DESCRIPTION
**Pull request by rsyring**
fixes audreyr/cookiecutter#629

Rough draft.  Let me know if you don't like this approach for any reason.

No tests for this change.  I looked at the current tests and didn't see anything test_hooks.py that was checking cleanup functionality.  Is that where the tests for this should go?

### CODE REVIEW

**Comment by audreyr** [comment]
Thanks! This looks good so far.

The test would go into https://github.com/audreyr/cookiecutter/blob/master/tests/test_generate_hooks.py.

**Comment by audreyr** [comment]
@rsyring If you add the test, this will be good to merge. Thanks!

**Comment by rsyring** [comment]
Ok, thanks for the feedback.  I'll also try to look into the concern raised here: https://github.com/audreyr/cookiecutter/issues/629#issuecomment-215406670

**Comment by pydanny** [comment]
@rsyring, you said in https://github.com/audreyr/cookiecutter/issues/629#issuecomment-215301460:

> With 33 open PRs, I'm hesitant to start a new one. That's not a criticism, I realize that's how OSS goes sometimes. I just don't want to spend on the time on the PR until this issue is acknowledged.

Since you wrote that @audreyr, @hackebrot, and @michaeljoseph, all unpaid volunteers, took to heart what you said and have given timely feedback.

However, it's been 19 days since your last response and we've yet to see any further developments. And on an issue you called "**really bad**".

Is there any reason why things haven't moved forward on your end?

**Comment by rsyring** [comment]
@pydanny Yes, the lack of current tests on this functionality raises the barrier a bit.  I also am not sure how the comments here will apply: https://github.com/audreyr/cookiecutter/issues/629#issuecomment-215406670

So this turned from a PR for a few lines to having to get my head deeper into CC as a whole.

I appreciate the comments that have been given.  This is a really bad bug and cost me some time restoring a project from backups.  I fixed it for me and have confirmed it works.  Fixing it for the project takes more time...something I have little of.

I never promised to fix it, I simply wanted to make sure that If I did take time to submit a PR, that it would get reviewed.  I did my part, you guys did your part.  Now, it seems, more work is needed on my part to finish. 

Right now, delivery dates for projects at work or my home life, even small ones, are often measured in terms of months.  I can't promise a delivery date on this PR, sorry.  You are welcome to finish it or close it if you find what I have done so far to be more hassle than it's worth.  

> That's not a criticism, I realize that's how OSS goes sometimes

:+1:

**Comment by michaeljoseph** [comment]
I'm happy to push this forward in a separate PR (I'm also a little worried about the semantics of `overwrite-if-exists` becoming `don't-delete-project-dir-on-failure`)

**Comment by rsyring** [comment]
@michaeljoseph just wondering if you you made any progress on this on a different PR or had any further thoughts?

**Comment by sodre** [comment]
@michaeljoseph 

It  has been a year since you self-assigned this PR. Would you be okay with me picking this up and adding the tests and documentation?

**Comment by michaeljoseph** [comment]
@sodre :grimacing: https://twitter.com/miketaylr/status/873175465321783296

I would normally jump at the opportunity to welcome a new contributor, but I had already written this code.
Thanks for the reminder and the offer to move this forward!

**Pull request closed without merging**
