### PR TITLE
Drop support for EOL Python 3.3

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/audreyr/cookiecutter/issues/1017.

Also add `python_requires` to setup.py to help pip, and PyPI Python version badges to READMEs.

### CODE REVIEW

**Comment by hackebrot** [comment]
Hi @hugovk! 👋 

Thank you for your contribution! Can you please resolve the conflicts?

**Comment by hugovk** [comment]
Done!

**Comment by hackebrot** [comment]
ping @michaeljoseph @pydanny 🍪

**Comment by hackebrot** [comment]
Thank you for your contribution to Cookiecutter @hugovk! 🍪

**Pull request merged**
