### PR TITLE
output_dir for python API invocation + parametrize output_dir tests

### PR DESCRIPTION
**Pull request by tony**
Need this for a cookiecutter project that's tested using [python api](http://cookiecutter.readthedocs.org/en/latest/advanced_usage.html#calling-cookiecutter-functions-from-python).

Also parametrize output_dir tests and add testcase for cookiecutter python object.

### CODE REVIEW

**Comment by tony** [comment]
@pydanny @audreyr : If the new tests look good, this will unblock me on one of my cookiecutters (https://github.com/tony/cookiecutter-flask-pythonic/commit/ff8a74ebe18e076a7da2ae9e047d690f70efcc58). I'm trying to get tests and TDD ramped up for boilerplates. When I get it smoothed out - maybe I can write a section on it

I can now avoid import problems when rerunning tests while watching files.

**Comment by cabello** [comment]
Dupe of #90 ?

**Comment by tony** [comment]
@cabello It appears so.

@davedash : It appears I have duplicated your issue.  I'd prefer to see you get credit, since you were first at it.

The only thing that differs is the tests.  I do like the extra assurances parametrizing gives in case anything is factored.  If those look ok we can always add it afterwards.

**Comment by jefftriplett** [comment]
Any updates on this issue by chance? I could really use it for a project and I'd prefer to not have to duplicate functionality to accomplish. Thanks!

**Comment by davedash** [comment]
Oh sorry I see my name is mentioned here - um, I think someone actively using cookiecutter should take this over - hopefully @tony , but honestly @jefftriplett if you're blocked I think it's fine to duplicate effort.

**Comment by pydanny** [comment]
We're planning to do a release of Cookiecutter tomorrow. We'll review this before then.

**Comment by jefftriplett** [comment]
Thank you for the quick response. I completely understand if it needs more time. Just thought I'd ask to see since it seemed like this PR covers a usecase I ran into tonight. Thanks everyone!

**Comment by pydanny** [comment]
This is going out with the 1.1.0 release. (#530)

**Comment by jefftriplett** [comment]
Thank y'all! :tada:

**Pull request closed without merging**
