### PR TITLE
Use new version too :+1:

### PR DESCRIPTION
**Pull request by stevepeak**
There 2.0.3 has a small bug fix. Thanks! The PyYaml dependency is removed.

### CODE REVIEW

**Comment by hackebrot** [comment]
Can you please also change https://github.com/audreyr/cookiecutter/blob/master/appveyor.yml?

**Comment by pydanny** [comment]
Also see https://github.com/audreyr/cookiecutter/issues/691

**Comment by audreyr** [comment]
Thanks for the codecov fix!

Taken care of in 3c4685f536afda3be93da3fe3039cec0ab0d60a3.

**Comment by hackebrot** [comment]
Hmm 😕 Looks the coverage is not combinedanymore? We've had 100% after also reporting via appveyor

**Comment by stevepeak** [comment]
@hackebrot this was due to an issue with detecting the merge commit in AppVeyor, which is fixed now. Thanks!

**Comment by hackebrot** [comment]
Thank you @stevepeak! 🙇

**Pull request closed without merging**
