### PR TITLE
Allow default config from main

### PR DESCRIPTION
**Pull request by hackebrot**
Please let me know your thoughts! 😄

### CODE REVIEW

**Comment by lamby** [comment]
Thank you for your quick reply. I am unclear about the goal of this alternative PR given that it leaves the offending kwarg intact and thus the output would still be unreproducible. Perhaps I did not explain the issue well enough in #800..?

**Comment by lamby** [comment]
Thank you for your quick reply. I am unclear about the goal of this alternative PR given that it leaves the offending kwarg intact and thus the output would still be unreproducible. Perhaps I did not explain the issue well enough in #800..?

**Comment by hackebrot** [comment]
Hey, I've now read the site that you've linked in #800.

If I understand correctly, this should then be changed all across the code base?
(``cli.py`` uses the same default)

This PR would allow to explicitly go with the default config when using the Python API to invoke Cookiecutter as opposed to running the CLI app.

**Comment by lamby** [comment]
> If I understand correctly, this should then be changed all across the code base?

Can you clarify what "this" refers to? But regardless, only the changes in #800 are required to ensure that the generated HTML documentation is reproducible.

I'm afraid my initial PR (#800) has still not been fully understood correctly; I am not sure why we are being distracted by changing the behaviour of default configs, etc. #800 does not intend to change any behaviour *except* the HTML output written by Sphinx.

**Comment by hackebrot** [comment]
Ah the documentation.. I see

**Comment by hackebrot** [comment]
https://cookiecutter.readthedocs.io/en/latest/cookiecutter.html#cookiecutter.config.get_user_config

**Comment by lamby** [comment]
Right, the documentation: http://i.imgur.com/0IAsIOK.jpg. Notice how it includes "/home/docs"?

Shall we close this PR and move to #800?

**Pull request closed without merging**
