### PR TITLE
cli: don't use unicode_literals to please click

### PR DESCRIPTION
**Pull request by vincentbernat**
The reason are explained in this thread:
 https://github.com/PythonCharmers/python-future/issues/22

Just remove unicode_literals from `cookiecutter/cli.py` as it is the
first use of click. However, it should also be removed from
`cookiecutter/prompt.py`.

### CODE REVIEW

**Comment by audreyr** [comment]
+1, I think this is a good idea. Thanks @vincentbernat.

**Comment by hackebrot** [comment]
Well done @vincentbernat :+1: 

Can you please redo the changes once we merge #495?
Otherwise I'll take care of updating ``cli`` and ``prompt``.

**Comment by vincentbernat** [comment]
Yes, no problem, just ping me when this is done.

**Comment by hackebrot** [comment]
Gogogo :rocket: :grin:

**Comment by vincentbernat** [comment]
Done!

**Comment by audreyr** [comment]
Merged. Thanks @vincentbernat and @hackebrot.

**Pull request merged**
