### PR TITLE
Asking AppVeyor to upload coverage info to codecov

### PR DESCRIPTION
**Pull request by ewjoachim**
An alternate take on #669 trying to get 100% coverage counting Windows specific lines, without adding new mocking tests

### CODE REVIEW

**Comment by ewjoachim** [comment]
It seems AppVeyor it not going to run this anytime soon. If this doesn't work, [this commit](https://github.com/jayvdb/python-appveyor-demo/commit/4330a51605aa9e71978e939a2215bfb80faa3cb9) may help (it shows someone succesfully attachig codecov to appveyor by adding the codecov call on ``test_success`` instead of ``on_success`` and adding coverage elements in "artifacts". As I only found that after pushing this commit, for now I'm just trying to see if my approach works, and otherwise, I'll try this one.

**Comment by michaeljoseph** [comment]
Looking good :sparkles: :+1:

**Comment by hackebrot** [comment]
Does codecov combine the reports from both travis and appveyor?

**Comment by ewjoachim** [comment]
@hackebrot I lloks like it does : on the [coverage report](https://codecov.io/github/audreyr/cookiecutter?ref=1be814de20bcdbc37ee95b56eecf27b6d6c25ee2), click on "Unified". It used to display only the list at the top, and now there are clearly 2 different kinds of build.

This being said, we can probably make the title look nicer. I've just added a few details, let's see if it goes well. If it does, then, I'll have nothing to add :)

**Comment by ewjoachim** [comment]
Seems good. Ready when you are ! :sparkles:

**Comment by ewjoachim** [comment]
Oh, do you want me to squash the commits into 1 single ?

**Comment by hackebrot** [comment]
Nah, you're fine. We usually dont' squash commits.

Many thanks for this @ewjoachim. 🙇 

I feel it's the better solution for getting the error callback in the coverage report.

**Comment by ewjoachim** [comment]
Many thanks to you @hackebrot and @michaeljoseph ! See you around !

**Comment by hackebrot** [comment]
We love contributions 😸 Please feel free to submit PRs and ask for help on getting started.

**Pull request merged**
