### PR TITLE
Add a Code of Conduct to the project

### PR DESCRIPTION
**Pull request by andreagrandi**

### CODE REVIEW

**Comment by hackebrot** [comment]
Hi @andreagrandi! 👋 

Thank you for your PR.

Cookiecutter contributors and maintainers are expected to follow the [PyPA Code of Conduct](https://www.pypa.io/en/latest/code-of-conduct/) as per our [README file](https://github.com/audreyr/cookiecutter#code-of-conduct).

**Comment by andreagrandi** [comment]
Hi @hackebrot !

Thanks to you for your quick reply. My fault I didn't see it :/

I was looking at this page https://github.com/audreyr/cookiecutter/community
and noticed it was "missing". Maybe GitHub could add a way to add a "custom" one like in your case?

Feel free to close this one as it's not needed.

Cheers

**Comment by hackebrot** [comment]
That's no problem at all.

I'd be happy to add the file that GitHub is expecting w/o changing Cookiecutter's Code of Conduct, meaning that we can copy the section from the README for instance. 🤔 

Thoughts @audreyr @pydanny @michaeljoseph @willingc?

**Comment by andreagrandi** [comment]
That could work too! When you click on "Propose" button, you can select from a couple of templates or you can copy-paste your own (I forgot about this in my previous message!). I think the file has to be named in the same way GitHub proposes, but apart from that, you are not tight to a specific "formula", you can have your own.

**Comment by pydanny** [comment]
Being more explicit is always good, especially when it comes to codes of conduct.

**Comment by hackebrot** [comment]
Great! Can you update this PR accordingly @andreagrandi? 😄

**Comment by andreagrandi** [comment]
@hackebrot hi! I've now updated the PR as you requested. Please note: commits are a bit messed (I did a mistake and I fixed with an additional commit etc....). I usually rebase on master with `-i` and squash commits to clean the history in these situations. If you are happy with the changes I can do (squash the commits) that as well.

Cheers

**Comment by hackebrot** [comment]
That's all right. I'll squash the commits when merging 😃 

Thank you for your contribution to Cookiecutter, @andreagrandi! 🙇 🍪

**Comment by willingc** [comment]
Thanks @andreagrandi :cake: :sunflower:

**Pull request merged**
