### PR TITLE
Add section "Continuous Delivery"

### PR DESCRIPTION
**Pull request by bittner**
Adds a link to painless-continuous-delivery cookiecutter template in new section

### CODE REVIEW

**Comment by hackebrot** [comment]
Hey @bittner! 👋 

Thanks for the PR. Can you please add a section to the templates' README file explaining what the post generation hook does?

**Comment by bittner** [comment]
@hackebrot Done. Added [a new section](https://github.com/painless-software/painless-continuous-delivery#under-the-hood) a minute ago.

**Comment by bittner** [comment]
Anything else I can do to make this PR getting merged?

**Comment by hackebrot** [comment]
Hey @bittner! 👋 

Thanks for adding the section. There's a typo in it ``coockiecutter``, would be great if you could fix that.

Adding your template to the list now 😄

**Pull request merged**
