### PR TITLE
Ability to specify an output_dir.

### PR DESCRIPTION
**Pull request by davedash**
This is only for the cookiecutter API, not for the commandline.

### CODE REVIEW

**Comment by tony** [comment]
It appears I duplicated this at https://github.com/audreyr/cookiecutter/issues/452. 

I would like to see #90 merged, I need that functionality for testing my boilerplate and using the cookie cutter python API.

@davedash: Can you rebase this against master?

**Comment by davedash** [comment]
Taking a look - might be a while been some time since I worked on this.

**Comment by tony** [comment]
@davedash Any idea what came up on the tests? It looks like there may have been encoding issues

**Comment by tony** [comment]
@davedash Can you check the travis build errors?

**Comment by davedash** [comment]
I'm on vacation until June. So I probably won't get a chance until then to
look. Sorry

**Comment by tony** [comment]
Are you ok if we close this and go with my PR?

**Comment by davedash** [comment]
Absolutely. Thanks tony.

**Comment by tony** [comment]
Ok, let's move this to https://github.com/audreyr/cookiecutter/pull/452.

**Pull request closed without merging**
