### PR TITLE
Fix the repo regex to handle + in URLs

### PR DESCRIPTION
**Pull request by habnabit**
The documentation said that you could do git+https:// or git+ssh:// but that was not, in fact, true.

### CODE REVIEW

**Comment by pydanny** [comment]
@habnabit We've tweaked the @appveyor integration. Can you bump this pull request so @appveyor runs again?

**Comment by habnabit** [comment]
@pydanny what is involved in a bump? I can delete and recreate the branch, but I don't know how github will take that. Or push an empty commit?

**Comment by pydanny** [comment]
@habnabit - That's where you make a tiny change to get CI to run again. No worries, I finally figured out how to restart it. :smile:

**Comment by pydanny** [comment]
Still breaking in @appveyor. Trying to debug...

**Comment by habnabit** [comment]
Anything I can do to help out with this?

**Comment by hackebrot** [comment]
Is the regex still compiled with ``VERBOSE`` on?

**Comment by storax** [comment]
`re.compile` takes flags as second argument. So in this case it is not compiled with `VERBOSE` on and needs `re.VERBOSE` as second argument. See [Python Regular expression Documentation](https://docs.python.org/2/library/re.html#re.VERBOSE).

**Comment by habnabit** [comment]
@hackebrot yes. I switched it to use `(?x)` instead, which is the inline flag for `VERBOSE`.

**Comment by storax** [comment]
Ah learned something new :+1:

**Comment by hackebrot** [comment]
Let's stick to ``re.VERBOSE`` :grimacing: Comprehensibility is key IMHO

btw Happy New Year!

**Comment by habnabit** [comment]
Will update soon.

**Comment by hackebrot** [comment]
:bell:

**Comment by hackebrot** [comment]
:bell:

**Comment by michaeljoseph** [comment]
@habnabit :bell:
Also, could you please add a test case to https://github.com/audreyr/cookiecutter/blob/master/tests/test_main.py?

**Pull request closed without merging**
