### PR TITLE
Choices in Context

### PR DESCRIPTION
**Pull request by hackebrot**
Add support for choices in a context as suggested in #441.

I noticed that we are using custom methods for retrieving the user input and decided to let ``click.prompt`` handle the Python2/Python3 compatibility matters. This PR requires thorough reviews and testing before merging it as I touched some core functions and I want to be certain I didn't break anything :exclamation: 

The CI might not detect these errors as most of the ``read_response`` calls are still ``monkeypatched``. I'm afraid we need to do some manual testing to be 100% positive that everyting is working as expected :sweat: 

I implemented several tests for the new functionality. :smiley: 

Please let me know your thoughts and I'll be happy to update this PR.

### CODE REVIEW

**Comment by hackebrot** [comment]
While testing this on https://github.com/hackebrot/cookiecutter-kivy/commit/58d2aa91e819508e99f385316e679a26411c883e I noticed that ``click`` has its own way of displaying default values in the prompt.

```
...
project_name (default is "Kivy Project")?  []: Test Choices
repo_name (default is "testchoices")?  []: 
project_short_description (default is "Cookiecutter template for applications built upon the kivy-framework.")?  []: 
release_date (default is "2014-05-15")?  []: 2015-04-18
year (default is "2014")?  []: 2015
version (default is "0.1.0")?  []: 
minimum_kivy_version (default is "1.8.0")?  []: 
Select orientation (default is "1"):
    1 - all
    2 - landscape
    3 - portrait
Choose from 1, 2, 3: [1]: 2
```

I would like to let ``click`` handle all the prompting, which means we should rewrite https://github.com/audreyr/cookiecutter/blob/master/cookiecutter/prompt.py#L48 too, however this will ultimately change the prompts:

``minimum_kivy_version (default is "1.8.0")?``

to

``minimum_kivy_version ["1.8.0"]:``

**Comment by hackebrot** [comment]
FYI @appveyor crash after 40 mins of doing nothing :sob:

**Comment by hackebrot** [comment]
I'd like to continue on this one, however I need to know if you approve the direction I'm heading with this PR. :construction_worker: 

:bell: @Pawamoy @audreyr @pydanny @michaeljoseph

**Comment by Pawamoy** [comment]
Well, you have my blessing :grinning: 
Seriously, yes, I approve, I am sure you know what you're doing, but my answer does not really count ;)
And thank you :exclamation:

**Comment by audreyr** [comment]
At a glance it looks good!

Although just FYI I didn't get a chance to study it in detail or check if there are any similar PRs in the queue.

**Comment by hackebrot** [comment]
Ty :bow:

I'm afraid we have several PRs covering topics such as **json to yaml**, **choices in variables** and **moving prompts to click**. :worried: 

I will submit a new PR for the latter this week hopefully without the choices feature, simply to get rid of compatibility handling for ``read_response``.

**Comment by pydanny** [comment]
I regards to your tweet, I think supporting variations of 'y' is a good thing. Specifically 'y', 'ye', and 'yes', all case insensitive.

**Pull request closed without merging**
