### PR TITLE
add github "ISSUE_TEMPLATE.md" file

### PR DESCRIPTION
**Pull request by luzfcb**
good new Github feature:
https://github.com/blog/2111-issue-and-pull-request-templates
https://help.github.com/articles/helping-people-contribute-to-your-project/

### CODE REVIEW

**Comment by luzfcb** [comment]
I did not understand codecov. coverage should not change, since I do not include or modified any python file . /o\

**Comment by pydanny** [comment]
:ping: @stevepeak

**Comment by michaeljoseph** [comment]
May be because Appveyor hasn't finished running yet...

**Comment by stevepeak** [comment]
@michaeljoseph that would be it 👍

**Comment by pydanny** [comment]
Is it possible to make @codecov-io wait for all the test runners to finish?

**Comment by stevepeak** [comment]
@pydanny it does, I checked the logs and it expresses that it did wait for AppVeyor to finish. Because I'm not familiar with the project I'm unable to account for the change in coverage.

- Here is the `utils` file on [0df6e730](https://codecov.io/gh/audreyr/cookiecutter/src/0df6e730770798b56066e080558ae669049e118c/cookiecutter/utils.py) the pr base
- And here is this commit [660226c](https://codecov.io/gh/audreyr/cookiecutter/src/660226c/cookiecutter/utils.py#L20)

Do you know why this line would suddenly be uncovered?

**Comment by michaeljoseph** [comment]
@stevepeak, that line only gets covered on Windows builds...

**Comment by michaeljoseph** [comment]
Looks like the [travis builds](https://codecov.io/gh/audreyr/cookiecutter/commit/660226c213fc031d5a847ac796e7ee23b06ae33d/builds) and [appveyor builds](https://codecov.io/gh/audreyr/cookiecutter/commit/9e9aea6ff3cc3045a095e2c0d2b4e515fa01b4b1/builds) aren't being combined?

**Comment by hackebrot** [comment]
Hey folks, we combined the reports from travis and appveyor in #670. Looks like it's not working anymore although we haven't changed anything in our configs? 😢

**Comment by audreyr** [comment]
@hackebrot I tried to look into it but couldn't figure it out. I thought it might have been related to me removing the quotation marks in 3c4685f536afda3be93da3fe3039cec0ab0d60a3, but I don't think that's it? @michaeljoseph, or were the quotation marks there for a special reason?

In the meantime I'm going to merge this, since it's unrelated and nice to have. Thanks @luzfcb.

**Comment by stevepeak** [comment]
@michaeljoseph looks like the merge commit is not being picked up by the uploader in AppVeyor. 9e9aea6f should be 660226c213f

I'm going to work on this now and report back asap

**Comment by michaeljoseph** [comment]
:+1: thanks @stevepeak!

**Comment by pydanny** [comment]
:+1: indeed to @stevepeak 😀

**Pull request merged**
