### PR TITLE
Added cookiecutter-pyqt5 template under Python cookiecutter packages

### PR DESCRIPTION
**Pull request by mandeepbhutani**
Cookiecutter-pyqt5 is a cookiecutter template that assists those who are wanting to create PyQt5 GUI applications. The cookiecutter assembles a PyQt5 GUI with tests written in Pytest. The test suite includes fixtures and tests using the Pytest-Qt, Pytest-Mock, and Pytest-Xvfb plugins that show the user how to test their GUI application. The cookiecutter also includes a fully functioning .travis.yml for users to quickly integrate with Travis CI.

### CODE REVIEW

**Comment by hackebrot** [comment]
Hi @mandeepbhutani 👋 

Thank you for submitting a template PR! Have you considered running tests with [pytest-cookies](https://github.com/hackebrot/pytest-cookies) against your template?

**Comment by mandeepbhutani** [comment]
Hi @hackebrot! Thanks for letting me know about pytest-cookies. I wish I had known about the plugin prior to building the template . I will write tests for the template and report back when they're complete.

**Comment by mandeepbhutani** [comment]
@hackebrot, I've written a basic test to test the template creation and all seems to be working well. 

https://github.com/mandeepbhutani/cookiecutter-pyqt5/blob/master/tests/test_template.py

**Comment by hackebrot** [comment]
Cool, that's awesome!

**Comment by mandeepbhutani** [comment]
Thanks!

**Pull request merged**
