### PR TITLE
Adding cookiecutter-django-essentials and cookiecutter-vansible to the list  of templates.

### PR DESCRIPTION
**Pull request by wldcordeiro**
Adding some additional templates to the list that people may find useful.

### CODE REVIEW

**Comment by wldcordeiro** [comment]
PR Bump.

**Comment by hackebrot** [comment]
I don't quite know the routine for validating cookiecutters. Hence I can't really help on this one.

I couldn't find an according section in the core committer guide (#421)

:bell: @audreyr @pydanny @pfmoore @michaeljoseph

**Comment by pydanny** [comment]
Apologies, haven't had time to do what is described at https://github.com/audreyr/cookiecutter/issues/421#issuecomment-85663557.

**Comment by pydanny** [comment]
Please rebase this commit so we can add it into our list. We'll handle it ASAP. Apologies for the delay.

**Comment by hackebrot** [comment]
Hi @wldcordeiro!

From what I can see the requirements of https://github.com/wldcordeiro/cookiecutter-django-essentials are insecure. At least this is what your badges states and it has a problem with your Django requirement.

**Comment by hackebrot** [comment]
:bell:

**Pull request closed without merging**
