### PR TITLE
Drop yaml libs use custom parser

### PR DESCRIPTION
**Pull request by hackebrot**
WIP :raised_hand:

Simple regex parser implementation for [user configs](https://cookiecutter.readthedocs.org/en/latest/advanced_usage.html#user-config-0-7-0) to replace **PyYAML AND ruamel.yaml**. Users on various platforms and Python versions seem to encounter various problems with both libs when installing **Cookiecutter**, which is a huge problem (see #557 :worried: ).

Please let me know your thoughts!

(Related to #568)

### CODE REVIEW

**Comment by hackebrot** [comment]
**Known issue:** Bad user configs do not cause an ``InvalidConfiguration`` error.

Won't update the tests until we are on the same page regarding the implementation. :point_left:

**Comment by pydanny** [comment]
Hooray to saying goodbye to the overkill of heavy-duty formal YAML libraries! That said, `config_parser` is really close to being `ConfigParser`. How about something like `simple_yaml` instead? That is a more obvious name, and lends itself to being separated out into a different, pure Python YAML parser project. :smile:

**Comment by hackebrot** [comment]
Note: See gitter

**Comment by audreyr** [comment]
@hackebrot Have you considered making this a separate library that we then include as a dependency?

**Comment by hackebrot** [comment]
Closing in favor of #621

**Pull request closed without merging**
